### ISSUE TITLE
sample_app構築の際のerror解明にご助力くださると嬉しいです、、、

### ISSUE THREAD

**Issue by 0xkf** [VWBL/VWBL-Sample-App#5]
# https://github.com/VWBL/VWBL-Sample-App/issues

アプリケーションをローカル環境でyarnから起動して、以下のようなエラーが出ました。

ウォレットへの接続や NFT周りの設定がうまく行ってなかったり？しますでしょうか。

この質問を解決するためにさらに詳細情報として必要なものがあれば教えてくだされば嬉しいです。

下記エラーメッセージです。

```javascript
Unhandled Runtime Error
Error: Returned error: execution reverted

Call Stack
Object.ErrorResponse
node_modules/web3/dist/web3.min.js (22:377547)
eval
node_modules/web3/dist/web3.min.js (22:376985)
eval
node_modules/web3/dist/web3.min.js (33:26729)\
```

設定している情報などは一部伏せ字で載せておきます。

```sh:ENV

NEXT_PUBLIC_PROVIDER_URL="https://eth-goerli.g.alchemy.com/v2/WmpLSxxxxxxxxxxxxxx"
NEXT_PUBLIC_NFT_CONTRACT_ADDRESS="0x09feD0BD9b9c9f6a52173E00e94dc9A2C31F4927"
NEXT_PUBLIC_VWBL_NETWORK_URL=https://vwbl.network
NEXT_PUBLIC_CHAIN_ID="5"
NEXT_PUBLIC_NFT_STORAGE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweDJBNDY2YzdGRDA0OUQ4QzNGRDE2YWRGQzVERDI4REIyYjg4M0Y2ODIiLCJpc3MiOiJuZnQtc3RvcmFnZSIsImlhdCI6MTY3MDY4OTAwMjgzMSwibmFtZSI6InRlc3QtdndibCJ9.VBSl5SYj2r6tISTBKxxxxxxxxxxxxxxxx"



```

**Comment by thashimoto1998** [comment]
VWBL Sample Appを触っていただきありがとうございます！

VWBLではTest用のdev環境においてmunbai(polygonのtestnet)を使用しておりますので、↓の環境変数で再度お試しいただいてよろしいでしょうか？
munbai上のnative token(MATIC)は[こちらのfaucet](https://faucet.polygon.technology/)から入手いただけます。

```
NEXT_PUBLIC_PROVIDER_URL=https://rpc-mumbai.maticvigil.com/
NEXT_PUBLIC_NFT_CONTRACT_ADDRESS=0x9850c4682475ac6bcB9CdA91F927CCc1574781C7
NEXT_PUBLIC_VWBL_NETWORK_URL=https://dev.vwbl.network
NEXT_PUBLIC_CHAIN_ID=80001
NEXT_PUBLIC_NFT_STORAGE_KEY=“ご自身のapi keyをご入力ください”
```

**Comment by 0xkf** [comment]
こちら、ありがとうございました〜!
自分でsample.app表示できるとことまで行き、とても嬉しかったです！

ちなみに、頂いたNEXT_PUBLIC_NFT_CONTRACT_ADDRESSにて記述されているコントラクトアドレスは、GitHubレポジトリ上の、vwbl-protocolにて、 NFTをデプロイした結果得られるものという認識であってますでしょうか？？

もしそうでしたら、そちらの方も開発してみたいと思っています。　


p.s.
Vwbl-protocol レポジトリ内の
Readme 2.write contract deployment script to script/deploy.js 
see VWBL docs for VWBL contracts already deployed 
に書かれている、VWBL DOCS という記述のリンクがうまく指定できてない気がするので、もしかしたら修正が必要かもしれません！

**Comment by thashimoto1998** [comment]
> こちら、ありがとうございました〜!
自分でsample.app表示できるとことまで行き、とても嬉しかったです！

再度していただきありがとうございます！

> ちなみに、頂いたNEXT_PUBLIC_NFT_CONTRACT_ADDRESSにて記述されているコントラクトアドレスは、GitHubレポジトリ上の、vwbl-protocolにて、 NFTをデプロイした結果得られるものという認識であってますでしょうか？？

はい、demo appはVWBL protocolの[VWBLMetadata contract](https://github.com/VWBL/VWBL-protocol/blob/master/contracts/access-condition/ERC721/extensions/VWBLMetadata.sol)をデプロイしています。

> p.s.
Vwbl-protocol レポジトリ内の
Readme 2.write contract deployment script to script/deploy.js
see VWBL docs for VWBL contracts already deployed
に書かれている、VWBL DOCS という記述のリンクがうまく指定できてない気がするので、もしかしたら修正が必要かもしれません！

リンク切れてました...
ありがとうございます！
